services:
  database_factory:
    class: App\Storage\Database\DatabaseFactory
    arguments: ['@settings']
  messenger:
    class: App\Messenger\Messenger
    arguments: ['@session']
  route_escaped_factory:
    class: App\Router\EscapedRoutePathFactory
  route_pattern_factory:
    class: App\Router\RoutePatternFactory
    arguments: ['@route_escaped_factory']
  route_factory:
    class: App\Router\RouteFactory
    arguments: ['@route_pattern_factory']
  route_collection_factory:
    class: App\Router\RouteCollectionFactory
    arguments: ['@route_factory']
  schema_collection_factory:
    class: App\Storage\Schema\StorageSchemaCollectionFactory
  session:
    class: App\Http\Session
  template_factory:
    class: App\Render\TwigTemplateFactory
    arguments: ['@twig']
  twig_loader:
    class: Twig\Loader\FilesystemLoader
    arguments: ['%templates_path%']
  twig:
    class: Twig\Environment
    arguments: ['@twig_loader']
