services:
  database_factory:
    class: App\Storage\Database\DatabaseFactory
    arguments: ['@settings']
  fund_storage:
    class: App\Storage\Sql\SqlFundStorage
    arguments: ['@database']
  security_storage:
    class: App\Storage\Sql\SqlSecurityStorage
    arguments: ['@database']
  fund_position_storage:
    class: App\Storage\Sql\SqlFundPositionStorage
    arguments: ['@database']
  portfolio_storage:
    class: App\Storage\Sql\SqlPortfolioStorage
    arguments: ['@database']
  messenger:
    class: App\Messenger\Messenger
    arguments: ['@session']
  json:
    class: App\Serialization\JsonDefault
  route_escaped_factory:
    class: App\Router\EscapedRoutePathFactory
  route_pattern_factory:
    class: App\Router\RoutePatternFactory
    arguments: ['@route_escaped_factory']
  route_factory:
    class: App\Router\RouteFactory
    arguments: ['@route_pattern_factory']
  route_collection_factory:
    class: App\Router\RouteCollectionFactory
    arguments: ['@route_factory']
  schema_collection_factory:
    class: App\Storage\Schema\StorageSchemaCollectionFactory
    arguments: ['@database_factory']
  session:
    class: App\Http\Session
  template_factory:
    class: App\Render\TwigTemplateFactory
    arguments: ['@twig']
  twig_loader:
    class: Twig\Loader\FilesystemLoader
    arguments: ['%templates_path%']
  twig:
    class: Twig\Environment
    arguments: ['@twig_loader']
