main:
  path: /
  controller: App\Route\MainController
  action: view
portfolios_view:
  path: /portfolios
  controller: App\Route\PortfoliosController
  action: view
portfolios_create_view:
  path: /portfolios/create
  controller: App\Route\PortfoliosController
  action: createView
portfolios_create_submit:
  path: /portfolios/create
  controller: App\Route\PortfoliosController
  action: createSubmit
  methods: [POST]
funds_view:
  path: /funds
  controller: App\Route\FundsController
  action: view
funds_edit_view:
  path: /funds/{symbol}/edit
  controller: App\Route\FundsController
  action: editView
funds_edit_submit:
  path: /funds/{symbol}/edit
  controller: App\Route\FundsController
  action: editSubmit
  methods: [POST]
funds_create_view:
  path: /funds/create
  controller: App\Route\FundsController
  action: createView
funds_create_submit:
  path: /funds/create
  controller: App\Route\FundsController
  action: createSubmit
  methods: [POST]
securities_view:
  path: /securities
  controller: App\Route\SecuritiesController
  action: view
overlap_view:
  path: /overlap
  controller: App\Route\OverlapController
  action: view
