portfolios_create_view:
  path: /portfolios/create
  controller: App\Route\PortfoliosController
  action: createView
portfolios_create_submit:
  path: /portfolios/create
  controller: App\Route\PortfoliosController
  action: createSubmit
  methods: [POST]
portfolios_view:
  path: /portfolios
  controller: App\Route\PortfoliosController
  action: view
funds_edit_view:
  path: /funds/{symbol}/edit
  controller: App\Route\FundsController
  action: editView
funds_edit_submit:
  path: /funds/{symbol}/edit
  controller: App\Route\FundsController
  action: editSubmit
  methods: [POST]
funds_delete_confirm:
  path: /funds/{symbol}/delete
  controller: App\Route\FundsController
  action: deleteConfirm
funds_delete_submit:
  path: /funds/{symbol}/delete
  controller: App\Route\FundsController
  action: deleteSubmit
  methods: [POST]
funds_create_view:
  path: /funds/create
  controller: App\Route\FundsController
  action: createView
funds_create_submit:
  path: /funds/create
  controller: App\Route\FundsController
  action: createSubmit
  methods: [POST]
funds_view:
  path: /funds/{symbol}
  controller: App\Route\FundsController
  action: view
funds_view_all:
  path: /funds
  controller: App\Route\FundsController
  action: viewAll
securities_delete_confirm:
  path: /securities/{symbol}/delete
  controller: App\Route\SecuritiesController
  action: deleteConfirm
securities_delete_submit:
  path: /securities/{symbol}/delete
  controller: App\Route\SecuritiesController
  action: deleteSubmit
  methods: [POST]
securities_view:
  path: /securities
  controller: App\Route\SecuritiesController
  action: view
overlap_view:
  path: /overlap
  controller: App\Route\OverlapController
  action: view
main:
  path: /
  controller: App\Route\MainController
  action: view
