schema:
  fund:
    class: App\Storage\Sql\Schema\SqlFundStorageSchema
  security:
    class: App\Storage\Sql\Schema\SqlSecurityStorageSchema
  fund_position:
    class: App\Storage\Sql\Schema\SqlFundPositionStorageSchema
  portfolio:
    class: App\Storage\Sql\Schema\SqlPortfolioStorageSchema
