schema:
  fund:
    class: App\Model\Schema\Sql\SqlFundStorageSchema
  security:
    class: App\Model\Schema\Sql\SqlSecurityStorageSchema
  fund_position:
    class: App\Model\Schema\Sql\SqlFundPositionStorageSchema
  portfolio:
    class: App\Model\Schema\Sql\SqlPortfolioStorageSchema
